tikiroom = Ride.create(name: "Walt Disney's Enchanted Tiki Room", description: "Theater in the round featuring Audio-Animatronic Characters", location_id: 1)
junglecruise = Ride.create(name: "Jungle Cruise", description: "River boat attraction", location_id: 1)
indianajones = Ride.create(name: "Indiana Jones Adventure: Temple of the Forbidden Eye", description: "Enhanced motion vehicle dark ride attraction", location_id: 1)
tarzan = Ride.create(name: "Tarzan's Treehouse", description: "Walk-through attraction", location_id: 1)
railroad = Ride.create(name: "Disneyland Railroad", description: "Railroad", location_id: 2)
mrlincoln = Ride.create(name: "Great Moments with Mr.Lincoln", description: "Stage show feauturing U.S. President Abraham Lincoln Audio-Animatronic", location_id: 2)
gallery = Ride.create(name: "The Disney Gallery", description: "Art work from Walt Disney Imagineering", location_id: 2)
cinema = Ride.create(name: "Main Street Cinema", description: "Movie Theater", location_id: 2)
pirates = Ride.create(name: "Pirates of the Caribbean", description: "Dark boat ride", location_id: 3)
hauntedmansion = Ride.create(name: "The Haunted Mansion", description: "Dark audio animatronics ghost ride", location_id: 3)
canoes = Ride.create(name: "Davy Crockett Explorer Canoes", description: "Free Floating Canoe Experience", location_id: 4)
pooh = Ride.create(name: "The many Adventures of Winnie the Pooh", description: "Full audio animatronics and trackless ride system", location_id: 4)
splash = Ride.create(name: "Splash Mountain", description: "Water ride with a drop", location_id: 4)
thunder = Ride.create(name: "Big Thunder Mountain Railroad", description: "Steel - Mine Train roller coaster", location_id: 5)
riverboat= Ride.create(name: "Mark Twain Riverboat", description: "Steamboat ride", location_id: 5)
island = Ride.create(name: "Pirate's Lair on Tom Sawyer Island", description: "Artificial Island", location_id: 5)
columbia = Ride.create(name: "Sailing Ship Columbia", description: "Sailing Ship Tour", location_id: 5)
goofy = Ride.create(name: "Goofy's Playhouse", description: "Tour to Goofy's house", location_id: 6)
donald = Ride.create(name: "Donald's Boat", description: "Tour to Donald's boat", location_id: 6)
gadget = Ride.create(name: "Gadget's Go Coaster", description: "A junior roller coaster", location_id: 6)
chipndale = Ride.create(name: "Chip 'n Dale's Treehouse", description: "Tour to the Treehouse", location_id: 6)
mickey = Ride.create(name: "Mickey's House and Meet Mickey", description: "Tour to Mickey Mouse and meet Mickey", location_id: 6)
minnie = Ride.create(name: "Minnie's House", description: "Tour to Minnie's house", location_id: 6)
rogerrabbit = Ride.create(name: "Roger Rabbit's Car Toon Spin", description: "Enter to Toowtown Cab Company. Dark ride", location_id: 6)
falcon = Ride.create(name: "Millennium Falcon: Smuggler's Run", description: "Motion Simulation Attraction", location_id: 7)
rise = Ride.create(name: "Star Wars: Rise of the Resistance", description: "A combined trackless dark ride, walk-through, motion simulator, and drop ride system", location_id: 7)


Location.create(name: "Adventureland")
Location.create(name: "Main Street, USA")
Location.create(name: "New Orleans Square")
Location.create(name: "Critter Country")
Location.create(name: "Frontierland")
Location.create(name: "Mickey's Toontown")
Location.create(name: "Star Wars: Galaxy's Edge")



User.create(username: "Steveo14", email:"steveo@gmail.com", password_digest: "Disneyland")
User.create(username: "EdithLavie", email:"edithlavie@gmail.com", password_digest: "Texas")
User.create(username: "EthanS", email:"ethans@gmail.com", password_digest: "Legos")

Review.create(title: "Best Ride Ever", content:"This is the best ride in the park.", user_id: 1, ride_id: 1)
Review.create(title: "Not my favorite", content:"The line is too long and the ride too short.", user_id: 2, ride_id: 3)
Review.create(title: "Great for little kids", content:"My little ones had a blast in this ride. The music is amazing.", user_id: 3, ride_id: 6)

